FoodieLog/foodie-log-server

core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
로그인 후 토큰으로 권한 체크안 안되는 현상 발견
-> hasRole() 의  'ROLE_' 접두어 때문에 발생한 오류
DB에 저장되는 'USER', 'ADMIN' 과의 통일성을 위해
hasRole() 대신 'ROLE_' 붙이지 않는 hasAuthority() 사용
Close #19
=> [Fix] #19 JWT 토큰 권한 체크 오류 해결 

application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java, application/src/main/java/com/foodielog/application/user/dto/KakaoDTO.java, application/src/main/java/com/foodielog/application/user/service/OauthUserService.java, application/src/main/resources/application-api.yml, application/src/main/resources/application.yml, core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java, core/src/main/java/com/foodielog/server/_core/util/CookieUtil.java, core/src/main/java/com/foodielog/server/_core/util/Fetch.java, core/src/main/java/com/foodielog/server/user/entity/User.java, core/src/main/java/com/foodielog/server/user/repository/UserRepository.java
카카오 로그인&회원가입 구현
1. 프론트 에서도 카카오 api 연결 필요 -> 추후 담당자에서 설명
2. 카카오 로그인과 동시에 회원가입 시, 닉네임 'kakao{ 사용자의 카카오 아이디(num) }'로 임의 설정
-> user(entity)의 nickName이 not null이기 때문
3. 카카오 간편 회원가입(우리 서비스 이용 약관 동의)는 비즈앱+비즈채널만 가능하여 검수 요청 함
Close #22
=> [Feat] #22 카카오 로그인&회원가입 구현

application/build.gradle, application/src/main/java/com/foodielog/application/_core/smtp/MailService.java, application/src/main/java/com/foodielog/application/_core/smtp/SMTPConfig.java, application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java, application/src/main/java/com/foodielog/application/user/dto/SignUpDTO.java, application/src/main/java/com/foodielog/application/user/dto/UserResponse.java, application/src/main/java/com/foodielog/application/user/dto/response/SendCodeDTO.java, application/src/main/java/com/foodielog/application/user/dto/response/VerifiedCodeDTO.java, application/src/main/java/com/foodielog/application/user/service/UserAuthService.java, application/src/main/java/com/foodielog/application/user/service/UserOauthService.java, application/src/main/java/com/foodielog/application/user/service/UserService.java, application/src/main/resources/application-api.yml, application/src/main/resources/application.yml, core/build.gradle, core/src/main/java/com/foodielog/server/_core/customValid/valid/ValidNickName.java, core/src/main/java/com/foodielog/server/_core/customValid/valid/ValidPassWord.java, core/src/main/java/com/foodielog/server/_core/customValid/validator/NickNameValidator.java, core/src/main/java/com/foodielog/server/_core/customValid/validator/PassWordValidator.java, core/src/main/java/com/foodielog/server/_core/error/MyExceptionHandler.java, core/src/main/java/com/foodielog/server/_core/redis/RedisConfig.java, core/src/main/java/com/foodielog/server/_core/redis/RedisService.java, core/src/main/java/com/foodielog/server/_core/s3/S3Uploader.java, core/src/main/java/com/foodielog/server/_core/util/JsonConverter.java, core/src/main/java/com/foodielog/server/user/entity/User.java, core/src/main/java/com/foodielog/server/user/repository/UserRepository.java, management/src/main/resources/application-api.yml, management/src/main/resources/application.yml
자체 회원가입 관련 api 구현
1. 코드 요청 api 는 가입용, 비밀번호 설정용 분리
- 가입시: 이메일 체크(중복되면 안됨)
- 비밀번호 설정 시: 이메일 체크(로그인 유저의 이메일)
2.  코드 검증 api는 하나로 통일 
1. api 가입 시 초기 설정용 이후 마이페이지에서 설정용 분리
- 초기 설정 시: 이미지 필수, 닉네임 필수, 자기소개 선택
- 마이페이지에서 설정 시: 로그인 유저 체크, 이미지 선택, 닉네임 필수, 자기소개 선택
Close #24
=> [Feat] #24 자체 회원가입 기능

application/src/main/java/com/foodielog/application/feed/controller/FeedController.java, application/src/main/java/com/foodielog/application/feed/service/FeedService.java, application/src/main/resources/application-api.yml, application/src/main/resources/application.yml, application/src/test/resources/application-api.yml, application/src/test/resources/application.yml, core/src/main/java/com/foodielog/server/_core/error/ErrorMessage.java, core/src/main/java/com/foodielog/server/_core/s3/S3Uploader.java, management/src/main/resources/application-api.yml, management/src/main/resources/application.yml, management/src/test/resources/application-api.yml, management/src/test/resources/application.yml
s3 uploader 리팩토링 완료
`백엔드`에서는 `피드 업로드 버튼`으로 이미지를 한번에 받기 때문에, 이미지 선택 시 실시간 체크는 `프론트`와 상의 해야함
Close #39
=> [Refactor] #39 S3 uploader 리팩토링

application/src/main/java/com/foodielog/application/user/controller/UserController.java, application/src/main/java/com/foodielog/application/user/dto/RestaurantFeedListDTO.java, application/src/main/java/com/foodielog/application/user/dto/UserFeedListDTO.java, application/src/main/java/com/foodielog/application/user/dto/UserRestaurantListDTO.java, application/src/main/java/com/foodielog/application/user/service/UserService.java, core/src/main/java/com/foodielog/server/feed/repository/FeedLikeRepository.java, core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java, core/src/main/java/com/foodielog/server/restaurant/repository/RestaurantLikeRepository.java, core/src/main/java/com/foodielog/server/user/repository/FollowRepository.java
마이페이지 맛집 지도 리스트, 맛집 상세페이지 구현 완료
피드 공유 Url 미처리
[카카오로 링크 공유하기 카카오 디벨로퍼 참고](https://developers.kakao.com/docs/latest/ko/message/common)
Close #28
=> [Feat] #28 마이페이지 맛집 리스트, 맛집 상세페이지 구현

application/src/main/java/com/foodielog/application/feed/service/FeedService.java
맛집 중복 시 맛집 반환 오류 수정
발생원인
1. 맛집 중복 체크 시 해당 맛집이 db에 존재할 경우 반환되는 맛집이 명시되어 있지 않음.
Close #52
=> [Fix] #52 맛집 중복 체크 오류 수정

application/src/main/java/com/foodielog/application/user/controller/UserSettingController.java, application/src/main/java/com/foodielog/application/user/dto/ChangeNotificationDTO.java, application/src/main/java/com/foodielog/application/user/dto/CheckBadgeApplyDTO.java, application/src/main/java/com/foodielog/application/user/dto/CreateBadgeApplyDTO.java, application/src/main/java/com/foodielog/application/user/service/UserSettingService.java, core/src/main/java/com/foodielog/server/_core/customValid/valid/ValidEnum.java, core/src/main/java/com/foodielog/server/_core/customValid/validator/EnumValidator.java, core/src/main/java/com/foodielog/server/_core/error/MyExceptionHandler.java, core/src/main/java/com/foodielog/server/admin/entity/BadgeApply.java, core/src/main/java/com/foodielog/server/admin/repository/BadgeApplyRepository.java, core/src/main/java/com/foodielog/server/user/entity/User.java
알림 설정, 뱃지 신청 구현
이미 신청 내역이 있는지 확인 후 신청하도록 해야할듯 해서
"뱃지 신청 내역(Y/N) 조회" api 추가함
그런데 이미 뱃지가 있는 사람이 신청할경우도 핸들링 해야할듯 함
뱃지 상태를 확인하는 api 추가 필요해보임
\* 커스텀 Valid을 RequestBody에서 사용 시 exception 핸들링이 안되는듯 함... 500 에러로 던져짐... 아직 해결 못함  
Close #58
=> [Feat]  #58 알림 설정, 뱃지 신청 구현

application/src/main/java/com/foodielog/application/feed/controller/FeedController.java, application/src/main/java/com/foodielog/application/feed/dto/MainFeedListDTO.java, application/src/main/java/com/foodielog/application/feed/service/FeedService.java, core/src/main/java/com/foodielog/server/feed/repository/FeedLikeRepository.java, core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java
- 메인 피드 구현
```Java
public MainFeedListDTO.Response getMainFeed(User user, Long feedId, Pageable pageable) {
LocalDateTime now = LocalDateTime.now();
LocalDateTime date = now.minusMonths(1);
List<Feed> mainFeeds = feedRepository.getMainFeed(user, feedId, 0L, Timestamp.valueOf(date), pageable);
}
```
- 한달 전 피드까지 가져오도록 기능을 구현
- feedId 에 대한 validation 은 `Multi Thread` 환경에서 삭제가 되어 피드가 검색이 안되는 현상이 있어 제거
- findById 와 같이 status 검색을 하지 않고 가능은 한 것으로 보이지만 페이징을 위한 Id 이며 validation 의 필요성이 안느껴져서 제거
Close #91
=> [Feat] #91 메인 피드 기능 구현

application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java, application/src/main/java/com/foodielog/application/user/dto/response/KakaoLoginResp.java, application/src/main/java/com/foodielog/application/user/service/UserOauthService.java, application/src/main/resources/application-api.yml, application/src/test/resources/application-api.yml, management/src/main/resources/application-api.yml, management/src/test/resources/application-api.yml
카카오 로그인 api 호출 시,
인가 코드 발급 리다이렉트 url과 토큰 발급 리다이렉트 url 이 일치해야한다는 조건이 있었음
현재는 인가 코드는 프론트 서버에서, 토큰은 백엔드 서버에서 발급하는 로직이라 토큰 발급 api 호출에서 에러가 발생
따라서 프론트에서 [인가코드 발급 -> 토큰 발급] 후 토큰을 백엔드에 전달하는 로직으로 변경
Close #109
=> [Fix] kakao login API 오류  

application/src/main/java/com/foodielog/application/feed/service/FeedService.java, application/src/main/java/com/foodielog/application/restaurant/service/RestaurantService.java, application/src/main/java/com/foodielog/application/user/service/UserService.java, core/src/main/java/com/foodielog/server/feed/repository/FeedLikeRepository.java, core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java, core/src/main/java/com/foodielog/server/user/repository/FollowRepository.java
- 피드 리스트 follow 값과 like 값 에러 사항 수정
- 메인 피드 자신의 피드까지 가져오는 부분 수정
Close #127 , #128
=> [Fix] #127, #128 follow 값 에러 및 like 값 에러 수정

core/src/main/java/com/foodielog/server/report/repository/ReportRepository.java, management/src/main/java/com/foodielog/management/report/service/ReportService.java
'신고 승인 10 회 초과 시 자동 차단' 기능에서 신고 횟수 카운트 하는 쿼리문 오류
contentId를 받아서 조건에 넣는게 아니라 count 에서 중복 제거 조건을 r.contentId로 지정해야 함
Close #131
=> [Fix] #131 신고 횟수 카운트 쿼리 수정

core/src/main/java/com/foodielog/server/_core/customValid/valid/ValidEnum.java, core/src/main/java/com/foodielog/server/_core/customValid/validator/EnumValidator.java, core/src/main/java/com/foodielog/server/admin/entity/BlockUser.java, core/src/main/java/com/foodielog/server/user/repository/UserRepository.java, management/src/main/java/com/foodielog/management/member/controller/MemberController.java, management/src/main/java/com/foodielog/management/member/dto/request/BlockReq.java, management/src/main/java/com/foodielog/management/member/dto/response/MemberListResp.java, management/src/main/java/com/foodielog/management/member/service/MemberService.java
- 회원 목록 조회 구현
- 영구 차단 구현
- ValidEnum nullable 기능 추가하여 default 는 false 인 상태로 null 값을 허용하게 하고 싶으면 true 로 바꾸어 사용 가능하도록 구현
- param 값으로 받을 때 ValidEnum 은 null 을 허용하지 않아 구현함
Close #133
=> [Feat] #133 회원 목록 조회 및 영구 차단 구현

application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java, core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java, management/src/main/java/com/foodielog/management/user/controller/UserAuthController.java
auth 컨트롤러 앞에 prefix(api 또는 admin) 추가 
user 서버의 auth/** -> api/auth/**
admin 서버의 auth/** -> admin/auth/**
Close #149
=> [Fix] #149 auth 컨트롤러 앞에 prefix(api 또는 admin) 추가 

application/src/main/java/com/foodielog/application/feed/controller/FeedController.java, core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
단일 피드 상세보기 토큰 없이 접속하도록 수정
Close #163
=> [Fix] #163 단일 피드 상세보기 토큰 없이 접속하도록 수정

application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java, application/src/main/java/com/foodielog/application/user/dto/response/ExistsKakaoResp.java, application/src/main/java/com/foodielog/application/user/service/UserOauthService.java
카카오 로그인 버튼 클릭 시 최초 연결인 경우에만 약관동의& 프로필 수정화면이 보여야함
때문에 최초 연결인지 확인할 수 있도록 이메일 중복체크 api 추가
Close #187
=> [Feat] #187  카카오 중복 체크 api 

application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
기본 이메일 체크와 동일하게 중복일 때 409를 보내도록 되어있는데
409인 경우 응답바디를 받을 수 없음
-> 중복 여부와 관계없이 코드 200으로 응답
Close #189
=> refactor: 카카오 중복체크 응답 상태코드 변경 (#189)

application/src/main/java/com/foodielog/application/user/service/UserAuthService.java, application/src/main/java/com/foodielog/application/user/service/UserSettingService.java, core/src/main/java/com/foodielog/server/_core/security/jwt/JwtTokenProvider.java
reissue 시 기존 엑세스 토큰 무효화 안됨
Close #197
=> [Fix] #197 reissue 시 토큰 무효화 로직 추가 

core/src/main/java/com/foodielog/server/user/repository/FollowRepository.java
- 차단 및 탈퇴 유저 팔로우에서 제외
```java
Optional<Follow> findByFollowingIdAndFollowedId(User following, User followed);
boolean existsByFollowingIdAndFollowedId(User following, User followed);
```
- 해당 쿼리에서는 Join 을 적용 시키지 않았습니다.
- `findByFollowingIdAndFollowedId` 는 팔로우 생성 및 언팔로우 시에 사용이 되어 이미 차단 및 탈퇴에 대한 유저는 전 단계에서 user 가 있는지 확인하기 때문에 제외 했습니다.
- `existsByFollowingIdAndFollowedId` 는 많은 곳에 사용이 되었는데 주로 피드에서 많이 사용되는 것으로 확인했습니다. 마찬가지로 피드는 차단 및 탈퇴 시에 피드 데이터가 삭제 처리로 되기 때문에 차단 및 탈퇴 된 유저로 인한 버그가 발생하지 않는다고 판단하여 제외 시켰습니다.
Close #209
=> [Fix] #209 차단 및 탈퇴 유저 팔로우에서 제외

core/src/main/java/com/foodielog/server/admin/repository/BadgeApplyRepository.java, management/src/main/java/com/foodielog/management/member/controller/MemberController.java, management/src/main/java/com/foodielog/management/report/controller/ReportController.java
관리자 뱃지 신청 목록, 탈퇴 회원  목록 조회 시 parma이 없어도 조회 가능하도록 수정
Close #211
=> [Fix] #211 관리자 뱃지 신청 목록 수정

core/src/main/java/com/foodielog/server/_core/util/CookieUtil.java
클라이언트에서 refreshToken 쿠키를 document.cookie로 접근할 수 없음
토큰 재발급 로직 구현을 위해 쿠키에 접근해야함 
쿠키의 도메인을 클라이언트 주소로 설정하지 않아 발생한 것으로 예상됨
Close #217
=> [Fix] #217 cookie domain 설정
