- .github/workflows/pr-test.yml
Actions을 이용한 CI - PR Test
develop, main 브랜치에 PR 시 자동 test 후 Report 생성
test 통과 시에만 PR merge 가능
[설정 참고](https://devs0n.tistory.com/25)
> Create pr-test.yml for CI(PR Test)

- src/main/java/com/foodielog/server/_core/error/MyExceptionHandler.java
- src/main/java/com/foodielog/server/_core/error/MyValidationHandler.java
- src/main/java/com/foodielog/server/_core/error/exception/Exception400.java
- src/main/java/com/foodielog/server/_core/error/exception/Exception401.java
- src/main/java/com/foodielog/server/_core/error/exception/Exception403.java
- src/main/java/com/foodielog/server/_core/error/exception/Exception404.java
- src/main/java/com/foodielog/server/_core/error/exception/Exception500.java
- src/main/java/com/foodielog/server/_core/util/ApiUtils.java
- src/main/java/com/foodielog/server/_core/util/DateUtils.java
- src/main/java/com/foodielog/server/_core/util/FilterResponseUtils.java
자주 사용되는 exception과 handler 정의
API 공통 응답 포맷을 위한 util 클래스 정의
Close #7
> [Feat] #7 Exception Handler & API 응답 Util 클래스 정의

- .github/workflows/pr-test.yml
> [Feat] actions 환경 변수 설정

- application/src/main/java/com/foodielog/application/reply/controller/ReplyController.java
- application/src/main/java/com/foodielog/application/reply/dto/ReplyRequest.java
- application/src/main/java/com/foodielog/application/reply/dto/ReplyResponse.java
- application/src/main/java/com/foodielog/application/reply/service/ReplyService.java
- core/src/main/java/com/foodielog/server/reply/entity/Reply.java
- core/src/main/java/com/foodielog/server/reply/repository/ReplyRepository.java
댓글 등록, 삭제, 리스트 기능 구현
- 댓글 리스트를 가져올 때 기존 페이징네이션을 사용하면 오프셋 기반으로 풀 스캔이 되어 커서 기반 방식으로 교체
- 변경 전
- 변경 후
Close #10
> [Feat] #10 댓글 등록 및 삭제 기능 구현 

- application/src/main/java/com/foodielog/application/feed/controller/FeedController.java
- application/src/main/java/com/foodielog/application/reply/controller/ReplyController.java
- application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
- core/src/main/java/com/foodielog/server/_core/error/MyValidationHandler.java
- core/src/main/java/com/foodielog/server/_core/error/exception/ValidationException.java
- core/src/main/java/com/foodielog/server/_core/util/ApiUtils.java
> [Refactor] #30 controller, exception 응답 포맷 수정

- core/src/main/java/com/foodielog/server/feed/entity/FeedLike.java
- core/src/main/java/com/foodielog/server/feed/entity/Media.java
- core/src/main/java/com/foodielog/server/notification/entity/Notification.java
- core/src/main/java/com/foodielog/server/user/entity/Follow.java
- core/src/main/java/com/foodielog/server/user/entity/FollowPK.java
follow 엔티티 복합키 설정, 미작성 된 어노테이션 추가
이슈 참조
Close #32
> [Refactor] #32 follow entity 복합키 설정

- application/src/main/java/com/foodielog/application/user/controller/UserController.java
- application/src/main/java/com/foodielog/application/user/dto/UserResponse.java
- application/src/main/java/com/foodielog/application/user/dto/response/UserFeedListDTO.java
- application/src/main/java/com/foodielog/application/user/dto/response/UserProfileDTO.java
- application/src/main/java/com/foodielog/application/user/dto/response/UserThumbnailDTO.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
- core/src/main/java/com/foodielog/server/feed/repository/FeedLikeRepository.java
- core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java
- core/src/main/java/com/foodielog/server/feed/repository/MediaRepository.java
- core/src/main/java/com/foodielog/server/reply/repository/ReplyRepository.java
- core/src/main/java/com/foodielog/server/restaurant/repository/RestaurantLikeRepository.java
- core/src/main/java/com/foodielog/server/user/repository/FollowRepository.java
- 마이페이지_my, other 기능 구현
- 사진 리스트_my, other 기능 구현
- 하나의 서비스는 여러 repository 에 대한 의존성을 가져도 될까?
- [인프런 Service 와 Repo 의 관계 질문](https://www.inflearn.com/questions/21703/service%EC%99%80-repository%EC%9D%98-%EA%B4%80%EA%B3%84%EC%97%90-%EB%8C%80%ED%95%9C-%EC%A7%88%EB%AC%B8%EC%9E%85%EB%8B%88%EB%8B%A4) 
- 서비스와 서비스끼리 의존성을 가져도 될까?
- 코드의 재사용성을 생각하면 괜찮을 수 있다.
- 서비스 레이어에서는 다른 레이어와 특징적으로 구분되는 트랜잭션을 관리하는 역할이 있으므로 트랜잭션에 대한 주의는 필요할 것 같다!
- [깃허브 토론 Service에서 Service를 의존할까? Repository를 의존할까?](https://github.com/woowacourse/retrospective/discussions/15)
Close #29
> [Feat] #29 마이페이지 기능

- .github/workflows/pr-test.yml
PR 시 actions가 Gradle Build Test도 하도록 설정
Close #42
> [Feat] #42 Build jobs 추가 

- application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
- application/src/main/java/com/foodielog/application/user/dto/LoginDTO.java
- application/src/main/java/com/foodielog/application/user/dto/ResetPasswordDTO.java
- application/src/main/java/com/foodielog/application/user/dto/SendCodeDTO.java
- application/src/main/java/com/foodielog/application/user/dto/SignUpDTO.java
- application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
- application/src/main/resources/data.sql
- core/src/main/java/com/foodielog/server/_core/customValid/valid/ValidPassword.java
- core/src/main/java/com/foodielog/server/_core/customValid/validator/PasswordValidator.java
- core/src/main/java/com/foodielog/server/user/entity/User.java
비밀번호 찾기(재설정) 구현 
변경하려는 비밀번호가 이전 비밀번호와 같아도 변경 수행(덮어쓰기) 
Close #45
> [Feat] #45 비밀번호 찾기(재설정) 구현 

- application/src/main/java/com/foodielog/application/feed/controller/FeedController.java
- application/src/main/java/com/foodielog/application/feed/dto/FeedRequest.java
- application/src/main/java/com/foodielog/application/feed/service/FeedService.java
- core/src/main/java/com/foodielog/server/_core/kakaoApi/KakaoApiResponse.java
- core/src/main/java/com/foodielog/server/restaurant/entity/Restaurant.java
- core/src/main/java/com/foodielog/server/restaurant/repository/RestaurantLikeRepository.java
- core/src/main/java/com/foodielog/server/restaurant/repository/RestaurantRepository.java
피드 등록 세부 기능 추가 구현
- 맛집 좋아요 체크 오류 해결법
`boolean` > `Boolean`으로 변경
**lombok으로 getter 생성할경우 isXXX 변수명은 getIsXXX이 아닌 isXXX으로 자동 설정된다.**
[참고 링크](https://kbwplace.tistory.com/167)
Close #47
> [Feat] #47 피드 등록 세부 기능 추가 구현

- application/src/main/java/com/foodielog/application/user/controller/UserSettingController.java
- application/src/main/java/com/foodielog/application/user/dto/ChangePasswordDTO.java
- application/src/main/java/com/foodielog/application/user/dto/ChangeProfileDTO.java
- application/src/main/java/com/foodielog/application/user/service/UserSettingService.java
- core/src/main/java/com/foodielog/server/user/entity/User.java
마이페이지 비밀번호, 프로필 설정 
1. 프로필 설정 구현 시 주의할 점
- 프로필 사진 변경 시 기존 사진은 버킷에서 삭제
- 닉네임 중복 체크 시  닉네임 미변경(사진이나 자기소개만 변경)인 경우 고려해야함
2. 🐛 버킷에서 이미지 삭제가 안되는 버그 발견. 담당자에게 전달 완료
Close #49
> [Feat] #49 마이페이지 비밀번호, 프로필 설정 

- application/src/main/resources/data.sql
- core/src/main/java/com/foodielog/server/feed/entity/FeedLike.java
- core/src/main/java/com/foodielog/server/notification/entity/Notification.java
- core/src/main/java/com/foodielog/server/notification/type/NotificationType.java
- core/src/main/java/com/foodielog/server/report/entity/Report.java
- management/src/main/resources/data.sql
> [Feat] #56 더미데이터 생성

- application/src/main/java/com/foodielog/application/user/dto/LoginDTO.java
프론트에서 피드, 마이페이지 구분을 위해서는 유저 id가 필요해보임
로그인 시 응답에 추가 
Close #59
> [Feat] #59 LoginDTO 응답 id값 추가 

- application/src/main/java/com/foodielog/application/feed/controller/FeedController.java
- application/src/main/java/com/foodielog/application/restaurant/controller/RestaurantController.java
- application/src/main/java/com/foodielog/application/restaurant/dto/LikedRestaurantDTO.java
- application/src/main/java/com/foodielog/application/restaurant/dto/RestaurantFeedListDTO.java
- application/src/main/java/com/foodielog/application/restaurant/service/RestaurantService.java
- application/src/main/java/com/foodielog/application/user/controller/UserController.java
- application/src/main/java/com/foodielog/application/user/dto/UserRestaurantListDTO.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
- core/src/main/java/com/foodielog/server/restaurant/repository/RestaurantLikeRepository.java
나의 맛집 지도 구현, 기존 코드 수정
Close #61
> [Feat] #61 나의 맛집 지도 구현

- application/src/main/java/com/foodielog/application/restaurant/controller/RestaurantController.java
- application/src/main/java/com/foodielog/application/restaurant/dto/LikeRestaurantDTO.java
- application/src/main/java/com/foodielog/application/restaurant/dto/UnlikeRestaurantDTO.java
- application/src/main/java/com/foodielog/application/restaurant/service/RestaurantService.java
맛집 좋아요, 좋아요 취소 구현
`api/restaurant` 로 통일시키기 위해서
`api/restaurant/like`, `api/restaurant/unlike` 로 수정
Close #66
> [Feat] #66 맛집 좋아요, 좋아요 취소 구현

- application/src/main/java/com/foodielog/application/user/controller/UserController.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
- core/src/main/java/com/foodielog/server/user/entity/Follow.java
> [Feat] #72 유저 팔로우, 언팔로우 구현

- application/src/main/java/com/foodielog/application/reply/service/ReplyService.java
- core/src/main/java/com/foodielog/server/reply/entity/Reply.java
- core/src/main/java/com/foodielog/server/reply/repository/ReplyRepository.java
- 삭제된 댓글이 조회가 되는 현상 수정
- 댓글 삭제의 status delete 에서 hidden 으로 변경
Close #74
> [Bug] #74 댓글 조회, 댓글 삭제 기능 수정

- application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
- application/src/main/java/com/foodielog/application/user/service/UserOauthService.java
- core/src/main/java/com/foodielog/server/_core/security/auth/PrincipalDetailsService.java
- core/src/main/java/com/foodielog/server/user/repository/UserRepository.java
> [Fix] #78 탈퇴, 차단한 유저 로그인 막기

- application/src/main/java/com/foodielog/application/user/controller/UserController.java
- application/src/main/java/com/foodielog/application/user/dto/UserSearchDTO.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
- core/src/main/java/com/foodielog/server/user/repository/UserRepository.java
> [Feat] #81 유저 검색 구현 

- application/src/main/java/com/foodielog/application/restaurant/service/RestaurantService.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
- application/src/main/resources/application.yml
- application/src/test/resources/application.yml
- core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java
- core/src/main/java/com/foodielog/server/reply/repository/ReplyRepository.java
- core/src/main/java/com/foodielog/server/user/repository/UserRepository.java
- management/src/main/resources/application.yml
- management/src/test/resources/application.yml
> [Fix] #78 삭제한 피드, 댓글 제외

- application/src/main/java/com/foodielog/application/_core/swagger/ApplicationSwaggerConfig.java
- application/src/main/java/com/foodielog/application/feed/controller/FeedController.java
- application/src/main/java/com/foodielog/application/feed/dto/UpdateFeedDTO.java
- application/src/main/java/com/foodielog/application/feed/service/FeedService.java
- core/src/main/java/com/foodielog/server/feed/entity/Feed.java
- core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java
- core/src/main/java/com/foodielog/server/reply/repository/ReplyRepository.java
피드 삭제, 수정 구현 
피드 수정은 현재 글만 수정 가능
Close #86
> [Feat] #86 피드 삭제, 수정 구현

- application/src/main/java/com/foodielog/application/reply/service/ReplyService.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
- core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java
- core/src/main/java/com/foodielog/server/reply/repository/ReplyRepository.java
> [Bug] #78 삭제된 피드 및 댓글 Validation 수정

- application/src/main/java/com/foodielog/application/reply/controller/ReplyController.java
- application/src/main/java/com/foodielog/application/reply/dto/ReportReplyDTO.java
- application/src/main/java/com/foodielog/application/reply/service/ReplyService.java
- core/src/main/java/com/foodielog/server/report/repository/ReportRepository.java
- core/src/main/java/com/foodielog/server/report/type/ReportReason.java
> [Feat] #94 댓글 신고 구현

- application/src/main/java/com/foodielog/application/reply/controller/ReplyController.java
- application/src/main/java/com/foodielog/application/reply/service/ReplyService.java
- reply 코드 개선 및 pageDefault 수정
#96
> [Fix] #96 reply 코드 개선 및 pageDefault 수정

- application/src/main/java/com/foodielog/application/_core/swagger/ApplicationSwaggerConfig.java
- application/src/main/java/com/foodielog/application/feed/dto/request/LikeFeedReq.java
- application/src/main/java/com/foodielog/application/feed/dto/request/ReportFeedReq.java
- application/src/main/java/com/foodielog/application/feed/dto/request/UpdateFeedReq.java
- application/src/main/java/com/foodielog/application/restaurant/controller/RestaurantController.java
swagger 주석 처리 제거, errors 제거
Close #107
> [Refactor] #107 swagger 주석 처리 제거, errors 제거

- application/src/main/java/com/foodielog/application/feed/controller/FeedController.java
- application/src/main/java/com/foodielog/application/feed/dto/response/MainFeedListResp.java
- application/src/main/java/com/foodielog/application/feed/service/FeedService.java
- application/src/main/java/com/foodielog/application/restaurant/controller/RestaurantController.java
- application/src/main/java/com/foodielog/application/restaurant/dto/response/RestaurantFeedListResp.java
- application/src/main/java/com/foodielog/application/restaurant/service/RestaurantService.java
- core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java
- core/src/main/java/com/foodielog/server/user/repository/FollowRepository.java
코드 포맷팅 수정 및 리팩토링
top3 부분은 해결방법을 찾지 못하여 보류
#96
> [Refactor] #96 코드 리팩토링

- application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
비밀번호를 인코딩 하지 않고 저장해서
회원가입 후 로그인이 안됨
Close #112
> [Fix} #112 비밀번호 인코딩 

- application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
- application/src/main/java/com/foodielog/application/user/controller/UserController.java
- application/src/main/java/com/foodielog/application/user/controller/UserSettingController.java
- application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
- application/src/main/java/com/foodielog/application/user/service/UserOauthService.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
- application/src/main/java/com/foodielog/application/user/service/UserSettingService.java
- core/src/main/java/com/foodielog/server/_core/error/MyExceptionHandler.java
- core/src/main/java/com/foodielog/server/user/entity/User.java
> [Refactor] #96 code refactor by chaewon

- application/src/main/java/com/foodielog/application/feed/controller/FeedController.java
- application/src/main/java/com/foodielog/application/reply/controller/ReplyController.java
- application/src/main/java/com/foodielog/application/user/controller/UserController.java
- application/src/main/java/com/foodielog/application/user/dto/response/UserFeedListResp.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
- application/src/main/java/com/foodielog/application/user/service/UserSettingService.java
- core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java
- core/src/main/java/com/foodielog/server/reply/repository/ReplyRepository.java
- 23.08.28 (월) 회의를 통해 전반적인 코드 개선에 대한 이슈 해결
- `RestaurantService` Top3 쿼리문 개선은 추후 변경 예정
- JPA Param 과 관련하여 [@Param 생략?](https://www.inflearn.com/questions/367372/param-%EC%83%9D%EB%9E%B5)
Close #96
> [Refactor] #96 전반적인 코드 개선

- application/src/main/java/com/foodielog/application/feed/controller/FeedController.java
- application/src/main/java/com/foodielog/application/feed/dto/response/FeedDetailResp.java
- application/src/main/java/com/foodielog/application/feed/service/FeedService.java
> [Feat] #117 단일 피드 상세보기 구현

- application/src/main/resources/data.sql
- build.gradle
- core/src/main/java/com/foodielog/server/user/repository/UserRepository.java
- management/src/main/java/com/foodielog/management/user/controller/UserAuthController.java
- management/src/main/java/com/foodielog/management/user/dto/request/LoginReq.java
- management/src/main/java/com/foodielog/management/user/dto/response/LoginResp.java
- management/src/main/java/com/foodielog/management/user/dto/response/ReissueResp.java
- management/src/main/java/com/foodielog/management/user/service/UserAuthService.java
- management/src/main/resources/data.sql
관리자 서버 로그인, 토큰 발급 구현
Close #120
> [Feat]  #120 관리자 서버 로그인, 토큰 발급 구현 

- application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
- application/src/main/java/com/foodielog/application/user/service/UserSettingService.java
- core/src/main/java/com/foodielog/server/_core/redis/RedisService.java
- core/src/main/java/com/foodielog/server/_core/smtp/MailService.java
- core/src/main/java/com/foodielog/server/_core/smtp/SMTPConfig.java
- core/src/main/java/com/foodielog/server/admin/entity/BlockUser.java
- core/src/main/java/com/foodielog/server/admin/repository/BlockUserRepository.java
- core/src/main/java/com/foodielog/server/admin/type/BlockReason.java
- core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java
- core/src/main/java/com/foodielog/server/reply/repository/ReplyRepository.java
- core/src/main/java/com/foodielog/server/report/entity/Report.java
- core/src/main/java/com/foodielog/server/report/repository/ReportRepository.java
- core/src/main/java/com/foodielog/server/user/entity/User.java
- management/src/main/java/com/foodielog/management/member/service/MemberService.java
- management/src/main/java/com/foodielog/management/report/controller/ReportController.java
- management/src/main/java/com/foodielog/management/report/dto/request/ProcessReq.java
- management/src/main/java/com/foodielog/management/report/service/ReportService.java
메일, 레디스 서비스 위치 이동 -> 리팩토링
신고 처리 기능 구현
신고 처리 요청 시 reportedId, contentId, status를 받으며 
reportedId + contentId( 신고당한 사람과 컨텐츠) 조합으로 모든 신고 내역을 가져와서 처리 
-> 한 글에 대해 여려명이 신고한 경우 고려
Close #125
> [Feat] #125 신고 처리 기능 구현

- application/src/main/java/com/foodielog/application/feed/dto/response/FeedDetailResp.java
- application/src/main/java/com/foodielog/application/feed/service/FeedService.java
> [Refactor] #124 단일 피드 맛집 정보 추가

- management/src/main/java/com/foodielog/management/member/service/MemberService.java
- 유저 차단 시에 삭제 처리 및 메일 전송 누락 부분 수정
Close #138
> [Fix] #138 유저 차단 시에 삭제 처리 및 메일 전송 수정

- application/src/main/java/com/foodielog/application/user/dto/response/KakaoLoginResp.java
- application/src/main/java/com/foodielog/application/user/dto/response/LoginResp.java
프론트 요청으로 로그인 API 응답값에 email 추가
Close #141
> [Refactor] #141 로그인 응답값 email 추가 

- application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
- management/src/main/java/com/foodielog/management/user/controller/UserAuthController.java
https healtycheck 컨트롤러 
Close #144
> [feat] #144 https healtycheck 컨트롤러 

- management/src/main/java/com/foodielog/management/report/controller/ReportController.java
- management/src/main/java/com/foodielog/management/report/service/ReportService.java
신고 승인 처리 후 관련 컨텐츠 삭제 
Close #137
> [Fix] #137 신고 승인 시 컨텐츠 삭제 

- application/src/main/java/com/foodielog/application/user/dto/response/UserProfileResp.java
> [Fix] #146 유저 프로필 닉네임 누락 수정

- application/src/main/java/com/foodielog/application/feed/dto/response/FeedDetailResp.java
- application/src/main/java/com/foodielog/application/feed/dto/response/MainFeedListResp.java
- application/src/main/java/com/foodielog/application/reply/dto/response/ReplyCreatResp.java
- application/src/main/java/com/foodielog/application/restaurant/dto/response/RestaurantFeedListResp.java
- application/src/main/java/com/foodielog/application/user/dto/response/UserFeedListResp.java
- 피드 및 댓글 userId 응답 값 추가
Close #148
> [Refactor] #148 피드 및 댓글 userId 응답 값 추가

- core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
CORS AllowedOrigins 설정
이슈는 해결 됐는지 확인 후 닫겠습니다
#152
> [Fix]  #152 CORS AllowedOrigins 설정

- core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
> fix: 서버 url 오타 수정

- application/src/main/java/com/foodielog/application/user/dto/response/KakaoLoginResp.java
- application/src/main/java/com/foodielog/application/user/dto/response/LoginResp.java
프론트엔드 요청으로 응답값 추가 
Close  #157
> [Refactor]  #157 로그인 응답값에 알림 설정 상태 추가

- application/src/main/resources/application.yml
- management/src/main/resources/application.yml
> [Feat] #159 서버 배포를 위한 yml 설정

- application/src/main/resources/application.yml
- application/src/main/resources/data.sql
- core/src/main/java/com/foodielog/server/admin/entity/BlockUser.java
- management/src/main/resources/application.yml
- management/src/main/resources/data.sql
더미데이터 수정 및 h2 설정 삭제
Close #161
> [Refactor] #161 더미데이터 수정

- core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
- core/src/main/java/com/foodielog/server/_core/security/jwt/JwtTokenProvider.java
> [Feat]  #166 서버 cors 및 토큰 설정

- application/src/main/java/com/foodielog/application/user/controller/UserAuthController.java
- application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
기존에는 필수 입력이기 때문에 isEmpty 체크 로직이 없었는데
선택 입력으로 변경되어 체크 로직도 추가
Close #173
> [Refactor] #173 회원가입 시 파일 선택 입력으로 변경 

- core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
AllowedOrigins URL 추가 
https://localhost:3001, https://192.168.0.3:3001, https://172.30.1.55:3001
#166
> [Feature] #166 AllowedOrigins 추가

- application/src/main/java/com/foodielog/application/_core/fcm/FcmInitializer.java
- application/src/main/java/com/foodielog/application/_core/fcm/FcmMessageProvider.java
- application/src/main/java/com/foodielog/application/feed/service/FeedService.java
- application/src/main/java/com/foodielog/application/notification/controller/NotificationController.java
- application/src/main/java/com/foodielog/application/notification/dto/request/NotificationTokenReq.java
- application/src/main/java/com/foodielog/application/notification/dto/response/NotificationListResp.java
- application/src/main/java/com/foodielog/application/notification/service/NotificationService.java
- application/src/main/java/com/foodielog/application/reply/service/ReplyService.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
- application/src/main/resources/application-api.yml
- application/src/test/resources/application-api.yml
- build.gradle
- core/src/main/java/com/foodielog/server/_core/redis/RedisService.java
- core/src/main/java/com/foodielog/server/notification/entity/Notification.java
- core/src/main/java/com/foodielog/server/notification/repository/NotificationRepository.java
- core/src/main/java/com/foodielog/server/user/entity/Follow.java
- core/src/main/java/com/foodielog/server/user/entity/FollowPK.java
- core/src/main/java/com/foodielog/server/user/repository/FollowRepository.java
- 알림 리스트 기능
- 알림 푸시 알림 기능
- 댓글, 피드 좋아요, 팔로우 시 알림 생성
Close #168
>  [Feat] #168 알림 기능 구현

- application/src/main/resources/application.yml
- application/src/main/resources/data.sql
- application/src/test/resources/application.yml
- management/src/main/resources/application.yml
- management/src/main/resources/data.sql
- management/src/test/resources/application.yml
> [Refactor] #164 더미데이터 수정

- core/src/main/java/com/foodielog/server/_core/error/MyExceptionHandler.java
ExceptionHandler 로그 출력 수정
지금 로그 출력이 너무 단순해서 정확한 원인 파악이 안됨
-[] ExceptionHandler 로그 출력 수정
> [Refactor] ExceptionHandler 로그 출력 수정

- application/src/main/java/com/foodielog/application/user/controller/UserController.java
- application/src/main/java/com/foodielog/application/user/dto/response/UserProfileResp.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
- 마이페이지 팔로우 상태 응답 누락 수정
Close #179
> [Fix] #179 마이페이지 팔로우 상태 응답 누락 수정

- core/src/main/java/com/foodielog/server/_core/s3/S3Uploader.java
s3 파일 저장 시 null check 추가
Close #181
> [Refactor] #181 s3 파일 저장 시 null 체크 추가

- application/src/main/java/com/foodielog/application/user/service/UserService.java
프로필에서 보여주는 회원 정보 오류 수정
Close #191
> [Fix] #191 프로필 회원 정보 오류 수정

- core/src/main/java/com/foodielog/server/feed/repository/FeedRepository.java
> [Fix] #193 메인 피드 리스트 페이징 오류 수정

- application/src/main/java/com/foodielog/application/feed/controller/FeedController.java
- application/src/main/java/com/foodielog/application/feed/dto/response/GetFeedResp.java
- application/src/main/java/com/foodielog/application/feed/service/FeedService.java
> [Feat] #195 알람용 단일 피드 보기 기능 구현

- application/src/main/java/com/foodielog/application/user/controller/UserController.java
- application/src/main/java/com/foodielog/application/user/dto/response/FollowListResp.java
- application/src/main/java/com/foodielog/application/user/dto/response/FollowerListResp.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
- core/src/main/java/com/foodielog/server/user/repository/FollowRepository.java
> [Feat] #199 팔로우, 팔로워 목록 기능 구현

- application/src/main/java/com/foodielog/application/user/dto/response/UserRestaurantListResp.java
- application/src/main/java/com/foodielog/application/user/service/UserService.java
업로드한 맛집 목록 응답값에 닉네임 추가
Close #202
> [Refactor] #202 업로드한 맛집 목록 응답값에 닉네임 추가

- application/src/main/java/com/foodielog/application/notification/dto/response/NotificationListResp.java
> [Fix] #201 알림 기능 시간 데이터 추가

- application/src/main/java/com/foodielog/application/feed/controller/FeedController.java
- application/src/main/java/com/foodielog/application/feed/dto/request/UpdateFeedReq.java
- application/src/main/java/com/foodielog/application/feed/service/FeedService.java
> [Refactor] #205 매핑 URL 수정

- core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
- core/src/main/java/com/foodielog/server/admin/entity/BadgeApply.java
- core/src/main/java/com/foodielog/server/notification/entity/Notification.java
ColumnDefault 값이 들어가지 않고 null로 들어감
Close #207
> [Fix] #207 ColumnDefault 값이 들어가지 않음

- application/src/main/java/com/foodielog/application/user/service/UserService.java
유저 맛집 지도 목록에서 맛집 중복 체크 로직 추가
Close #213
> [Fix] #213 유저 맛집 지도 목록에서 맛집 중복 체크 추가

- application/src/main/java/com/foodielog/application/reply/controller/ReplyController.java
- application/src/main/java/com/foodielog/application/reply/dto/request/ReplyCreateReq.java
- application/src/main/java/com/foodielog/application/reply/dto/response/ReplyCreateResp.java
- application/src/main/java/com/foodielog/application/reply/service/ReplyService.java
- application/src/main/java/com/foodielog/application/user/service/UserAuthService.java
- application/src/main/java/com/foodielog/application/user/service/UserOauthService.java
- core/src/main/java/com/foodielog/server/_core/security/SecurityConfig.java
- core/src/main/java/com/foodielog/server/_core/security/jwt/JwtAuthenticationFilter.java
- core/src/main/java/com/foodielog/server/_core/security/jwt/JwtTokenProvider.java
- management/src/main/java/com/foodielog/management/user/service/UserAuthService.java
리팩토링이 필요한 코드들 수정
- 오타, 필요없는 코드 제거 
- 시큐리티 설정 수정 
#215
> [Refactor] #215 출시 전 점검, 리팩토링 

- core/src/main/java/com/foodielog/server/_core/util/CookieUtil.java
쿠키 도메인 설정 시 프로토콜 제거하여 설정 
#217
> [Fix] #217 cookie domain 주소 수정 
